In [1]:
%run hyper-elasticity_debug.py

[[0.]
 [0.]
 [1.]]
[[0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]]
[[1. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
  1.69e-01
  7.58e-02
  1.07e-02
  3.43e-04
  7.44e-07


In [2]:
whos

Variable       Type        Data/Info
------------------------------------
DbarF          ndarray     3x3x3x3x1: 81 elems, type `float64`, 648 bytes
F              ndarray     3x3x3x3x1: 81 elems, type `float64`, 648 bytes
Fn             float64     6.0
G              function    <function <lambda> at 0x7f0ae2f12710>
G_K_dF         function    <function <lambda> at 0x7f0ae2f12830>
Ghat4          ndarray     3x3x3x3x3x3x1: 729 elems, type `float64`, 5832 bytes
I              ndarray     3x3x3x3x1: 81 elems, type `float64`, 648 bytes
I4             ndarray     3x3x3x3x3x3x1: 729 elems, type `float64`, 5832 bytes
I4rt           ndarray     3x3x3x3x3x3x1: 729 elems, type `float64`, 5832 bytes
I4s            ndarray     3x3x3x3x3x3x1: 729 elems, type `float64`, 5832 bytes
II             ndarray     3x3x3x3x3x3x1: 729 elems, type `float64`, 5832 bytes
K              ndarray     3x3x1: 9 elems, type `float64`, 72 bytes
K4             ndarray     3x3x3x3x3x3x1: 729 elems, type `float64`, 5832 b

In [3]:
tmp_1 = fft(F)
tmp_1.shape

(3, 3, 3, 3, 1)

In [4]:
Ghat4.shape

(3, 3, 3, 3, 3, 3, 1)

In [12]:
F_rand = np.random.rand(*F.shape)

In [14]:
np.linalg.norm(F_rand)

5.067310580750068

In [ ]:
# Function to compute the curl of a vector field component
def compute_curl(U, V, W):
    curl_x = np.gradient(W, axis=2) - np.gradient(V, axis=3)
    curl_y = np.gradient(U, axis=3) - np.gradient(W, axis=1)
    curl_z = np.gradient(V, axis=1) - np.gradient(U, axis=2)
    return np.array([curl_x, curl_y, curl_z])

def curl_F(F): # F in shape [3,3,nx,ny,nz]
    # Initialize an array to store the curl of the tensor field
    curl_F = np.zeros((3, 3, *F.shape[2:]))

    # Compute the curl for each component of the stress tensor
    for i in range(3):
        for j in range(3):
            curl_F[i, j] = compute_curl(F[(i+1)%3, (j+1)%3], F[(i+2)%3, (j+1)%3], F[(i+2)%3, (j+2)%3])

    # curl_F is the resulting field
    return curl_F

In [18]:
G??

In [20]:
tmp_2 = ddot42(Ghat4, tmp_1)
tmp_2.shape

(3, 3, 3, 3, 1)

In [21]:
tmp_3 = ifft(tmp_2)
tmp_3.shape

(3, 3, 3, 3, 1)

In [22]:
tmp_3.reshape(-1).shape

(81,)

In [24]:
%less hyper-elasticity_debug.py

In [25]:
who

DbarF	 F	 Fn	 G	 G_K_dF	 Ghat4	 I	 I4	 I4rt	 
I4s	 II	 K	 K4	 K_dF	 Nx	 Ny	 Nz	 P	 
Q	 Z	 b	 constitutive	 dFm	 ddot42	 ddot44	 delta	 dot11	 
dot22	 dot24	 dot42	 dyad22	 fft	 freq	 i	 ifft	 iiter	 
itertools	 j	 l	 m	 mu	 ndim	 norm	 np	 param	 
phase	 q	 shape	 sp	 tmp_1	 tmp_2	 tmp_3	 trans2	 x	 



In [29]:
mu.shape

(3, 3, 1)

In [ ]:
q